services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db # <--- Aggiungi questa riga
      - SQLALCHEMY_DATABASE_URI=postgresql://flask:passwordhere@db:5432/blog

  db: # <--- Il nome deve essere "db"
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: flask
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: passwordhere