apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-devops
  template:
    metadata:
      labels:
        app: flask-devops
    spec:
      containers:
      - name: flask-app
        image: ghcr.io/batz02/flask_devops:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql://flask:password123@postgres-service:5432/blog"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-devops-service
spec:
  type: LoadBalancer
  selector:
    app: flask-devops
  ports:
  - port: 80
    target_port: 8080