apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app # Etichetta univoca
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: ghcr.io/batz02/flask_devops:latest
        ports:
        - containerPort: 8080
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql://flask:password123@postgres-service:5432/blog"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-devops-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app # Deve essere IDENTICO a sopra
  ports:
  - port: 80
    targetPort: 8080