apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-devops
spec:
  replicas: 1 # Teniamo 1 per stabilità durante i test, poi puoi risalire a 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: ghcr.io/batz02/flask_devops:latest
        env:
        - name: DATABASE_HOST
          value: "postgres-service"
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql://flask:passwordhere@postgres-service:5432/blog"
---
---
apiVersion: v1
kind: Service
metadata:
  name: flask-devops-service
spec:
  type: LoadBalancer # K3s userà il ServiceLB per esporre l'app sulla porta 80 della VM
  selector:
    app: flask-app
  ports:
  - port: 80         # Porta pubblica
    targetPort: 8080 # Porta del tuo Flask